### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###

GET http://localhost:3000/api/events
Authorization: Basic matheus 123456

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "admin",
  "sourceIp": "192.168.9.10",
  "deviceName": "PC-01"
}

###

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_SUCCESS",
  "username": "pedro",
  "sourceIp": "192.168.0.20",
  "deviceName": "PC-02"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "admin",
  "sourceIp": "192.168.0.50",
  "deviceName": "PC-01"
}

### Buscar todos os alertas

GET http://localhost:3000/api/alerts

###

GET http://localhost:3000/api/alerts/1

### Alterar alerta para INVESTIGATING

PATCH http://localhost:3000/api/alerts/1/status
Content-Type: application/json

{
  "status": "INVESTIGATING"
}

###

PATCH http://localhost:3000/api/alerts/1/status
Content-Type: application/json

{
  "status": "RESOLVED"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "pedro",
  "sourceIp": "10.0.0.50",
  "deviceName": "PC-01"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "maria",
  "sourceIp": "10.0.0.50",
  "deviceName": "PC-01"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "joao",
  "sourceIp": "10.0.0.50",
  "deviceName": "PC-01"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "suporte",
  "sourceIp": "10.0.0.50",
  "deviceName": "PC-01"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "davi",
  "sourceIp": "10.0.0.50",
  "deviceName": "PC-01"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_FAILED",
  "username": "financeiro",
  "sourceIp": "10.0.0.99",
  "deviceName": "PC-FIN-01"
}

###

POST http://localhost:3000/api/events
Content-Type: application/json

{
  "eventType": "LOGIN_SUCCESS",
  "username": "financeiro",
  "sourceIp": "10.0.0.99",
  "deviceName": "PC-FIN-01"
}

### Simular Brute Force
POST http://localhost:3000/api/simulator/brute-force

### Password Spraying
POST http://localhost:3000/api/simulator/password-spraying

### Account Compromise
POST http://localhost:3000/api/simulator/account-compromise

### Registrar usuário

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "matheus",
  "password": "123456"
}

### Login

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "matheus",
  "password": "123456"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "pedro",
  "password": "qualquercoisa"
}

###

GET http://localhost:3000/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtYXRoZXVzIiwiaWF0IjoxNzg4MTczNjA4LCJleHAiOjE3ODgxNzcyMDh9.9jhp-I4was-qzJLm0qch4NGi7pUXquQ7Gz4W2HZQaSs

###

GET http://localhost:3000/api/events

###

GET http://localhost:3000/api/events
Authorization: Bearer token-qualquer

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "usuario-que-nao-existe",
  "password": "123456"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "matheus",
  "password": "senha-errada"
}

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testeEmail",
  "email": "teste@email.com",
  "password": "123456"
}

###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "teste@email.com",
  "password": "123456"
}

###
GET http://localhost:3000/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZUBlbWFpbC5jb20iLCJpYXQiOjE3ODg0NjM4MTYsImV4cCI6MTc4ODQ2NzQxNn0.tLRRGqIuA_WHx_LT-XG917kAv_royGWMzAsTGSyEep4

###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testeResponse",
  "email": "response@teste.com",
  "password": "123456"
}


### 1. Cadastro válido
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "testevalidacao",
  "email": "testevalidacao@email.com",
  "password": "123456"
}


### 2. Cadastro inválido - username vazio, email inválido e senha vazia
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "username": "",
  "email": "email-invalido",
  "password": ""
}


### 3. Login válido
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testevalidacao@email.com",
  "password": "123456"
}


### 4. Login inválido - email inválido e senha vazia
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "abc",
  "password": ""
}


### 5. Rota protegida - eventos
GET http://localhost:3000/api/events
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXZhbGlkYWNhb0BlbWFpbC5jb20iLCJpYXQiOjE3ODg0Njg3NTEsImV4cCI6MTc4ODQ3MjM1MX0.WLozgCRAD0x9gX8XQOezplGNJPAhp4cJdIhF2Q0A2ao


### 6. Buscar alertas
GET http://localhost:3000/api/alerts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXZhbGlkYWNhb0BlbWFpbC5jb20iLCJpYXQiOjE3ODg0Njg3NTEsImV4cCI6MTc4ODQ3MjM1MX0.WLozgCRAD0x9gX8XQOezplGNJPAhp4cJdIhF2Q0A2ao


### 7. Alterar status do alerta - válido
PATCH http://localhost:3000/api/alerts/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXZhbGlkYWNhb0BlbWFpbC5jb20iLCJpYXQiOjE3ODg0Njg3NTEsImV4cCI6MTc4ODQ3MjM1MX0.WLozgCRAD0x9gX8XQOezplGNJPAhp4cJdIhF2Q0A2ao

{
  "status": "RESOLVED"
}


### 8. Alterar status do alerta - inválido
PATCH http://localhost:3000/api/alerts/1/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0ZXZhbGlkYWNhb0BlbWFpbC5jb20iLCJpYXQiOjE3ODg0Njg3NTEsImV4cCI6MTc4ODQ3MjM1MX0.WLozgCRAD0x9gX8XQOezplGNJPAhp4cJdIhF2Q0A2ao

{
  "status": null
}